### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by SpyderDoesStuff** [jinergenkai/TokyoNight#1]
hi,
thank you for making this theme usable for visual studio. i really enjoy it!
i was wondering if you were planning on updating this theme for future releases of the original theme or is this the only release you plan on doing?
i was just curious because i really enjoyed using this theme in vs code and im happy that i can now use it in visual studio.
the choice is up to you tho. i was just curious.
thank you!

**Comment by jinergenkai** [comment]
hi, i just created conversion theme from vscode. show if i have problem of that theme not compatible with visual studio version i will try to fix it. On the contrary, if someone advises me on some features that make me excited, I will try it.

**Comment by SpyderDoesStuff** [comment]
ok. That answered my question, thanks!
